"" Vim Stuff
set nocompatible

" Enable filetype and syntax plugins
filetype plugin on
filetype indent on
syntax on

" Vim Gui Config
set guioptions-=r       " Remove right-hand scroll bar
set guioptions-=L       " Remove left-hand scroll bar
set guioptions-=b       " bottom scroll bar
set number              " Show the line number
set showmatch           " Show matching brackets.
set autochdir           " Automatically change window's cwd to file's dir
set confirm             " get a dialog when :q, :w, or :wq fails
set autoread            " Watch for external changes of a file
set ruler		        " show current position
set magic	        	" magic for regular expression
set showcmd		        " display incomplete commands
set clipboard=unnamed   " Enable system clipboard
set termguicolors       " right terminal colors!

" List completions
set wildmenu
set wildmode=full
set wildignore=*.o,*~,*.pyc,*.DS_STORE,*.db,node_modules/**,*.jpg,*.png,*.gif

"" Encoding set UTF-8 encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8
set fenc=utf-8
set termencoding=utf-8

" Real programmers don't use TABs but spaces
set tabstop=2
set softtabstop=0
set shiftwidth=2
set shiftround
set expandtab

"" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Disbale backups
set nobackup
set noswapfile
set nowritebackup

" Vim-Plug init
call plug#begin('~/.vim/plugged')

" Vim Packages {

    " Themes & Visual look and feel
    Plug 'vim-airline/vim-airline'
    Plug 'altercation/vim-colors-solarized'
    Plug 'whatyouhide/vim-gotham'

" }
" Add plugins to &runtimepath
call plug#end()


"=========================================
"" Vim Look and Feel Configuration
"=========================================

" Color scheme {
    "colorscheme solarized      " Classic Dark Solarized
    colorscheme gotham          " Gotham dark theme
"}


"=========================================
"" Bundles Configuration
"=========================================

" Airline Status {
    set laststatus=2
    set guifont=Hack:h12

    let g:airline_powerline_fonts = 1
    let g:airline#extensions#hunks#enabled = 1
    let g:airline#extensions#branch#enabled = 1
    let g:airline#extensions#tagbar#enabled = 1

    " Tabline
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#show_tab_type = 0
    let g:airline#extensions#tabline#show_close_button = 1
    let g:airline#extensions#tabline#show_splits = 0
    let g:airline#extensions#tabline#show_buffers = 0
    let g:airline#extensions#tabline#left_sep = ' '
    let g:airline#extensions#tabline#left_alt_sep = '|'
    let g:airline#extensions#tabline#buffer_min_count = 1
    let g:airline#extensions#tabline#tab_min_count = 1
    let g:airline_exclude_preview=1
    let airline#extensions#tabline#ignore_bufadd_pat =
            \ '\c\vgundo|undotree|vimfiler|tagbar|nerd_tree'
" }